export const galleryImages = {
  shawl_1: [
    {
      name: 'Black 2',
      url: '/imgs/shawl_black/shawl_black_close.jpg',
      imgWidth: 480,
      imgHeight: 300,
      top: 152,
      left: -75,
      scrollSpeed: 220,
    },
    {
      name: 'Black 3',
      url: '/imgs/shawl_black/shawl_black_front.jpg',
      imgWidth: 380,
      imgHeight: 400,
      top: 80,
      left: 75,
      scrollSpeed: 100,
    },
    {
      name: 'Black 1',
      url: '/imgs/shawl_black/shawl_black_model.jpg',
      imgWidth: 400,
      imgHeight: 450,
      top: 70,
      left: 2,
      scrollSpeed: 130,
    },
  ],
  shawl_2: [
    {
      name: 'Pink 2',
      url: '/imgs/shawl_pink/shawl_pink_side.jpg',
      imgWidth: 480,
      imgHeight: 300,
      top: 152,
      left: -75,
      scrollSpeed: 220,
    },
    {
      name: 'Pink 3',
      url: '/imgs/shawl_pink/shawl_pink_close.jpg',
      imgWidth: 380,
      imgHeight: 400,
      top: 80,
      left: 75,
      scrollSpeed: 100,
    },
    {
      name: 'Pink 1',
      url: '/imgs/shawl_pink/shawl_pink_front.jpg',
      imgWidth: 400,
      imgHeight: 450,
      top: 70,
      left: 2,
      scrollSpeed: 130,
    },
  ],
  shawl_3: [
    {
      name: 'White 2',
      url: '/imgs/shawl_white/shawl_white_1_close.jpg',
      imgWidth: 480,
      imgHeight: 300,
      top: 152,
      left: -75,
      scrollSpeed: 220,
    },
    {
      name: 'White 3',
      url: '/imgs/shawl_white/shawl_white_front_1.jpg',
      imgWidth: 380,
      imgHeight: 400,
      top: 80,
      left: 75,
      scrollSpeed: 100,
    },
    {
      name: 'White 1',
      url: '/imgs/shawl_white/shawl_white_model_2.jpg',
      imgWidth: 400,
      imgHeight: 450,
      top: 70,
      left: 2,
      scrollSpeed: 130,
    },
  ],
  about: [
    {
      name: 'About',
      url: '/imgs/about.jpg',
      imgWidth: 350,
      imgHeight: 480,
      top: 50,
      left: 50,
      scrollSpeed: 120,
    },
  ],
};

export const galleryDescriptions = {
  shawl_1: {
    orientation: 'left',
    headline: 'Szürke és kék selyemfonalak, tüll selymek fekete felvetésben, takácsmintával. Tervezett asszimetria.',
    text: 'A takácsminták és a fonalak vastagságának váltogatásával igazán izgalmas textúrát kaphatunk. A tüll fonal használatával a kendő könnyű, szinte áttetsző.  Egy ilyen kendő viselésekor az ember különlegesnek érezheti magát és biztos lehet benne, hogy mindenki észreveszi.',
    subText: 'Model: my mentor, Judit Lukacs',
  },
  shawl_2: {
    orientation: 'right',
    headline: 'Barack és rózsaszín mulberry selymet, púder rózsaszín alpaka- selyem keverék fonalat, fehér és mályva selyemtüllt szőttem pink felvetésbe.',
    text: 'Van, hogy az ember leül a szövőszék elé és csak nekiáll szőni, máskor pontos tervet készít… és olyan is van, amikor az előre eltervezett rendtől eltér és teljesen mást alkot. Egy kendőnél fontosak az arányok még aszimmetrikus mintázás esetén is. Ez egy nem mindennapi darab, igazán feltűnő kiegészítő.',
    subText: '',
  },
  shawl_3: {
    orientation: 'left',
    headline: 'Selyem felvetésben szőni varázslatos, ugyanakkor nagy odafigyelést igénylő munka, ami sok gyakorlást igényel. A selyem csúszik és nyúlik, így gondosan kell tartani a szálat, hogy a szövet sűrűsége egyenletes, a széle pedig penge éles legyen. A képen látható kendő pont az egyszerűségétől kiemelkedő.',
    text: 'Magyarországon, de talán Európában egyedülálló módon Judit Lukács műhelyében áll egy selyem felvetésű szövőszék. Ezen a széken csak különleges, 100% tiszta selyem kendők készülhetnek.',
    subText: '',
  },
  about: {
    orientation: 'right',
    headline: 'Tünde vagyok, szövés és fonalak nélkül elképzelhetetlennek tartom az életem.',
    text: '',
    subText: '',
  },
};
