export const galleryImages = {
  shawl_1: [
    {
      name: 'Planned Asimmetry 3',
      url: '/imgs/shawl_black/shawl_black_close.jpg',
      imgWidth: 480,
      imgHeight: 300,
      top: 152,
      left: -75,
      scrollSpeed: 220,
    },
    {
      name: 'Planned Asimmetry 2',
      url: '/imgs/shawl_black/shawl_black_front.jpg',
      imgWidth: 380,
      imgHeight: 400,
      top: 80,
      left: 75,
      scrollSpeed: 100,
    },
    {
      name: 'Planned Asimmetry 1',
      url: '/imgs/shawl_black/shawl_black_model.jpg',
      imgWidth: 400,
      imgHeight: 450,
      top: 70,
      left: 2,
      scrollSpeed: 130,
    },
  ],
  shawl_2: [
    {
      name: 'Pink with weaver pattern 3',
      url: '/imgs/shawl_pink/shawl_pink_side.jpg',
      imgWidth: 480,
      imgHeight: 300,
      top: 85,
      left: 25,
      scrollSpeed: 100,
    },
    {
      name: 'Pink with weaver pattern 2',
      url: '/imgs/shawl_pink/shawl_pink_front.jpg',
      imgWidth: 360,
      imgHeight: 480,
      top: 60,
      left: -130,
      scrollSpeed: 100,
    },
    {
      name: 'Pink with weaver pattern 1',
      url: '/imgs/shawl_pink/shawl_pink_close.jpg',
      imgWidth: 350,
      imgHeight: 470,
      top: 90,
      left: -50,
      scrollSpeed: 100,
    },
  ],
  shawl_3: [
    {
      name: 'Pure Silk 3',
      url: '/imgs/shawl_white/shawl_white_1_close.jpg',
      imgWidth: 300,
      imgHeight: 450,
      top: 70,
      left: 85,
      scrollSpeed: 100,
    },
    {
      name: 'Pure Silk 2',
      url: '/imgs/shawl_white/shawl_white_front_1.jpg',
      imgWidth: 480,
      imgHeight: 310,
      top: 160,
      left: -80,
      scrollSpeed: 220,
    },
    {
      name: 'Pure Silk 1',
      url: '/imgs/shawl_white/shawl_white_model_2.jpg',
      imgWidth: 350,
      imgHeight: 480,
      top: 70,
      left: 2,
      scrollSpeed: 130,
    },
  ],
};

export const galleryDescriptions = {
  shawl_1: {
    orientation: 'left',
    headline: 'Gray and blue silk with tulle in a black warp, worked into weaver patterns.',
    text: 'Mixing weaver patterns and the widths of threads resulted in an exciting texture. Using tulle makes this shawl light, almost transparent. Make yourself noticed, feel special while wearing a piece like this.',
    subText: 'Model: Judit Lukacs',
  },
  shawl_2: {
    orientation: 'right',
    headline: 'Peach and pink mulberry silk, powder pink alpaca-silk threads with white and mallow tulle woven into a pink warp.',
    text: 'Sometimes you just sit down at the loom and start weaving. Sometimes you make a plan. And sometimes you have a plan, but you deviate from it and create something entirely different to end up with a bold, offbeat accessory.',
    subText: '',
  },
  shawl_3: {
    orientation: 'left',
    headline: 'The simplicity of pure silk makes this shawl outstanding.',
    text: 'While it demands great care and lots of practice, weaving in a silk warp is magical. Silk is slippery and stretchy, the thread must be held with care to make the density even, the edges razor-sharp.',
    subText: '',
  },
};
