export const galleryImages = {
  shawl_1: [
    {
      id: 1,
      name: 'Planned Asimmetry 3',
      url: '/imgs/shawl_black/shawl_black_close_1200.png',
      thumb: '/imgs/thumbs/shawl_black_close_thumb.png',
      imgWidth: 550,
      imgHeight: 350,
      top: 90,
      left: -75,
      scrollSpeed: 100,
    },
    {
      id: 2,
      name: 'Planned Asimmetry 2',
      url: '/imgs/shawl_black/shawl_black_front_1200.png',
      thumb: '/imgs/thumbs/shawl_black_front_thumb.png',
      imgWidth: 380,
      imgHeight: 480,
      top: 120,
      left: 75,
      scrollSpeed: 220,
    },
    {
      id: 3,
      name: 'Planned Asimmetry 1',
      url: '/imgs/shawl_black/shawl_black_model_1200.png',
      thumb: '/imgs/thumbs/shawl_black_model_thumb.png',
      imgWidth: 400,
      imgHeight: 600,
      top: 70,
      left: 2,
      scrollSpeed: 130,
    },
  ],
  shawl_2: [
    {
      id: 4,
      name: 'Pink with weaver pattern 3',
      url: '/imgs/shawl_pink/shawl_pink_side_1200.png',
      thumb: '/imgs/thumbs/shawl_pink_side_thumb.png',
      imgWidth: 550,
      imgHeight: 350,
      top: 95,
      left: 0,
      scrollSpeed: 95,
    },
    {
      id: 5,
      name: 'Pink with weaver pattern 2',
      url: '/imgs/shawl_pink/shawl_pink_front_1200.png',
      thumb: '/imgs/thumbs/shawl_pink_front_thumb.png',
      imgWidth: 400,
      imgHeight: 600,
      top: 120,
      left: -170,
      scrollSpeed: 220,
    },
    {
      id: 6,
      name: 'Pink with weaver pattern 1',
      url: '/imgs/shawl_pink/shawl_pink_close_1200.png',
      thumb: '/imgs/thumbs/shawl_pink_close_thumb.png',
      imgWidth: 380,
      imgHeight: 550,
      top: 90,
      left: -85,
      scrollSpeed: 130,
    },
  ],
  shawl_3: [
    {
      id: 7,
      name: 'Pure Silk 3',
      url: '/imgs/shawl_white/shawl_white_1_close_1200.png',
      thumb: '/imgs/thumbs/shawl_white_1_close_thumb.png',
      imgWidth: 380,
      imgHeight: 550,
      top: 60,
      left: 75,
      scrollSpeed: 100,
    },
    {
      id: 8,
      name: 'Pure Silk 2',
      url: '/imgs/shawl_white/shawl_white_front_1_1200.png',
      thumb: '/imgs/thumbs/shawl_white_front_1_thumb.png',
      imgWidth: 550,
      imgHeight: 350,
      top: 150,
      left: -100,
      scrollSpeed: 220,
    },
    {
      id: 9,
      name: 'Pure Silk 1',
      url: '/imgs/shawl_white/shawl_white_model_2_1200.png',
      thumb: '/imgs/thumbs/shawl_white_model_2_thumb.png',
      imgWidth: 400,
      imgHeight: 600,
      top: 70,
      left: -10,
      scrollSpeed: 130,
    },
  ],
};

export const galleryDescriptions = {
  shawl_1: {
    orientation: 'left',
    headline: 'Gray and blue silk with tulle in a black warp, worked into weaver patterns.',
    text: 'Mixing weaver patterns and the widths of threads resulted in an exciting texture. Using tulle makes this shawl light, almost transparent. Make yourself noticed, feel special while wearing a piece like this.',
    subText: 'Model: Judit Lukacs',
  },
  shawl_2: {
    orientation: 'right',
    headline: 'Peach and pink mulberry silk, powder pink alpaca-silk threads with white and mallow tulle woven into a pink warp.',
    text: 'Sometimes you just sit down at the loom and start weaving. Sometimes you make a plan. And sometimes you have a plan, but you deviate from it and create something entirely different to end up with a bold, offbeat accessory.',
    subText: '',
  },
  shawl_3: {
    orientation: 'left',
    headline: 'The simplicity of pure silk makes this shawl outstanding.',
    text: 'While it demands great care and lots of practice, weaving in a silk warp is magical. Silk is slippery and stretchy, the thread must be held with care to make the density even, the edges razor-sharp.',
    subText: '',
  },
};
